version: '3.7'

services:
    nodejs:
        container_name: vue_training_nodejs
        build:
            context: ./
            dockerfile: ./docker/nodejs/Dockerfile
        user: '1000:1001'
        ports:
            - '8088:8080'
        volumes:
            - ./:/var/www/html
